reorder_imports = true
imports_granularity = "Crate"
use_small_heuristics = "Max"
max_width = 80
comment_width = 80
format_code_in_doc_comments = true
wrap_comments = true
binop_separator = "Back"
trailing_comma = "Vertical"
use_field_init_shorthand = true
reorder_impl_items = true